[vowels]
"рдЕ" = "ЁСВГ"
"рдЖ" = "ЁСВД"
"рдЗ" = "ЁСВЕ"
"рдИ" = "ЁСВЖ"
"рдЙ" = "ЁСВЗ"
"рдК" = "ЁСВИ"
"рдЛ" = "ЁСВйЁСВ▒"
"реа" = "ЁСВйЁСВ▓"
"рдМ" = "ЁСВкЁСВ▒"
"реб" = "ЁСВкЁСВ▓"
"рдО" = "ЁСВЙ"
"рдП" = "ЁСВЙ"
"рдР" = "ЁСВК"
"рдТ" = "ЁСВЛ"
"рдУ" = "ЁСВЛ"
"рдФ" = "ЁСВМ"
"рдН" = "ЁСВЙ"
"рдС" = "ЁСВД"

[vowel_marks]
"рд╛" = "\U000110b0"
"рд┐" = "\U000110b1"
"реА" = "\U000110b2"
"реБ" = "\U000110b3"
"реВ" = "\U000110b4"
"реГ" = "\U000110b9ЁСВйЁСВ▒"
"реД" = "\U000110b9ЁСВйЁСВ▓"
"рев" = "\U000110b9ЁСВкЁСВ▒"
"рег" = "\U000110b9ЁСВкЁСВ▓"
"реЖ" = "\U000110b5"
"реЗ" = "\U000110b5"
"реИ" = "\U000110b6"
"реК" = "\U000110b7"
"реЛ" = "\U000110b7"
"реМ" = "\U000110b8"
"реЕ" = "\U000110b0"
"реЙ" = "\U000110b7"

[yogavaahas]
"рдВ" = "\U00011081"
"рдГ" = "\U00011082"
"рдБ" = "\U00011080"

[virama]
"реН" = "\U000110b9"

[consonants]
"рдХ" = "ЁСВН"
"рдЦ" = "ЁСВО"
"рдЧ" = "ЁСВП"
"рдШ" = "ЁСВР"
"рдЩ" = "ЁСВС"
"рдЪ" = "ЁСВТ"
"рдЫ" = "ЁСВУ"
"рдЬ" = "ЁСВФ"
"рдЭ" = "ЁСВХ"
"рдЮ" = "ЁСВЦ"
"рдЯ" = "ЁСВЧ"
"рда" = "ЁСВШ"
"рдб" = "ЁСВЩ"
"рдв" = "ЁСВЫ"
"рдг" = "ЁСВЭ"
"рдд" = "ЁСВЮ"
"рде" = "ЁСВЯ"
"рдж" = "ЁСВа"
"рдз" = "ЁСВб"
"рди" = "ЁСВв"
"рдк" = "ЁСВг"
"рдл" = "ЁСВд"
"рдм" = "ЁСВе"
"рдн" = "ЁСВж"
"рдо" = "ЁСВз"
"рдп" = "ЁСВи"
"рд░" = "ЁСВй"
"рд▓" = "ЁСВк"
"рд╡" = "ЁСВл"
"рд╢" = "ЁСВм"
"рд╖" = "ЁСВн"
"рд╕" = "ЁСВо"
"рд╣" = "ЁСВп"
"рд│" = "ЁСВкЁСВ║"
"рдХреНрд╖" = "ЁСВНЁСВ╣ЁСВн"
"рдЬреНрдЮ" = "ЁСВФЁСВ╣ЁСВЦ"

[symbols]
"реж" = "реж"
"рез" = "рез"
"реи" = "реи"
"рей" = "рей"
"рек" = "рек"
"рел" = "рел"
"рем" = "рем"
"рен" = "рен"
"рео" = "рео"
"реп" = "реп"
"реР" = "ЁСВЛЁСВБ"
"рд╜" = "рд╜"
"ред" = "ЁСГА"
"рее" = "ЁСГБ"

[extra_consonants]
"рдХрд╝" = "ЁСВН"
"рдЦрд╝" = "ЁСВО"
"рдЧрд╝" = "ЁСВП"
"рдЬрд╝" = "ЁСВФ"
"рдбрд╝" = "ЁСВЩ"
"рдврд╝" = "ЁСВЫ"
"рдлрд╝" = "ЁСВд"
"рдпрд╝" = "ЁСВи"
