[vowels]
"เค" = "๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เฅ" = "๐ฉ๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เฅก" = "๐ฉ๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"

[vowel_marks]
"เคพ" = "๐ฉ"
"เคฟ" = "๐ฉ"
"เฅ" = "๐ฉ๐ฉ"
"เฅ" = "๐ฉ"
"เฅ" = "๐ฉ๐ฉ"
"เฅ" = "๐ฉ"
"เฅ" = "๐ฉ๐ฉ"
"เฅข" = "๐ฉ"
"เฅฃ" = "๐ฉ๐ฉ"
"เฅ" = "๐ฉ"
"เฅ" = "๐ฉ"
"เฅ" = "๐ฉ"
"เฅ" = "๐ฉ"
"เฅ" = "๐ฉ"
"เฅ" = "๐ฉ"

[yogavaahas]
"เค" = "๐ช"
"เค" = "๐ช"
"เค" = "๐ช"

[virama]
"เฅ" = "\U00011a98"

[consonants]
"เค" = "๐ฉ"
"เค" = "๐ฉ"
"เค" = "๐ฉ"
"เค" = "๐ฉ"
"เค" = "๐ฉ"
"เค" = "๐ฉต"
"เค" = "๐ฉถ"
"เค" = "๐ฉท"
"เค" = "๐ฉค"
"เค" = "๐ฉฅ"
"เค" = "๐ฉฆ"
"เค" = "๐ฉง"
"เคก" = "๐ฉจ"
"เคข" = "๐ฉฉ"
"เคฃ" = "๐ฉช"
"เคค" = "๐ฉซ"
"เคฅ" = "๐ฉฌ"
"เคฆ" = "๐ฉญ"
"เคง" = "๐ฉฎ"
"เคจ" = "๐ฉฏ"
"เคช" = "๐ฉฐ"
"เคซ" = "๐ฉฑ"
"เคฌ" = "๐ฉฒ"
"เคญ" = "๐ฉณ"
"เคฎ" = "๐ฉด"
"เคฏ" = "๐ฉป"
"เคฐ" = "๐ฉผ"
"เคฒ" = "๐ฉฝ"
"เคต" = "๐ฉพ"
"เคถ" = "๐ฉฟ"
"เคท" = "๐ช"
"เคธ" = "๐ช"
"เคน" = "๐ช"
"เคณ" = "๐ฉฝ"
"เคเฅเคท" = "๐ช"
"เคเฅเค" = "๐ฉท๐ช๐ฉฅ"

[symbols]
"เฅฆ" = "0"
"เฅง" = "1"
"เฅจ" = "2"
"เฅฉ" = "3"
"เฅช" = "4"
"เฅซ" = "5"
"เฅฌ" = "6"
"เฅญ" = "7"
"เฅฎ" = "8"
"เฅฏ" = "9"
"เฅ" = "๐ฉ๐ฉ๐ช"
"เคฝ" = ""
"เฅค" = "\U00011a9b"
"เฅฅ" = "\U00011a9c"
